name: Build & Test

on:
  workflow_call:
    inputs:
      run_tests:
        type: boolean
        default: true

    outputs:
      test_result:
        value: $ {{ jobs.build-test.outputs.test_result }}

jobs:
  build-test:
    outputs:
      test_result: ${{ steps.check_result.outputs.result }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest

    steps:
      - name: Check out Code
        uses: actions/checkout@v4

      - name: Setup language run time
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run flake8 test only if run_test is true
        id: check_result
        if: ${{ inputs.run_tests == true }}
        run: |
          flake8 app.py tests/
          if [ $? -eq 0]; then
           echo "result=passed" >> $GITHUB_OUTPUT
          else 
           echo "result=failed" >> $GITHUB_OUTPUT
