name: Docker build & push

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

      tag:
        type: string
        required: true

    outputs:
      image_url: # ← what the caller reads
        value: ${{ jobs.docker-build-push.outputs.image_url }}

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
      DOCKER_TAG: ${{ inputs.tag }}

    outputs:
      image_url: ${{ steps.set_url.outputs.image_url }} # ← feeds workflow_call output

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub PAT
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag image. # There also an alternate way for it (reusable generates SHA)
        run: |
          IFS=',' read -ra TAGS <<< "${{ inputs.tag }}"
          BUILD_CMD="docker build"
          for t in "${TAGS[@]}"; do
            BUILD_CMD="$BUILD_CMD -t ${{ vars.DOCKERHUB_USER }}/${{ inputs.image_name }}:$t"
          done
          BUILD_CMD="$BUILD_CMD ."
          eval $BUILD_CMD

      - name: Push all tags
        run: |
          IFS=',' read -ra TAGS <<< "${{ inputs.tag }}"
          for t in "${TAGS[@]}"; do
            docker push ${{ vars.DOCKERHUB_USER }}/${{ inputs.image_name }}:$t
          done

      - name: Output image URL
        id: set_url
        run: |
          echo "image_url=${{ vars.DOCKERHUB_USER }}/${{ inputs.image_name }}:$DOCKER_TAG" >>$GITHUB_OUTPUT
